creacion de la funcion para media desconocida solamente falta tener l…
angel-tapia/Prueba-Hipotesis pull request #3
Opened 2022-11-21 02:01 UTC by JSuarezIbarra

…a funcion de buscar en la tabla T

2022-11-21 02:12 UTC, angel-tapia requested changes

2022-11-21 02:12 UTC, angel-tapia commented on Media_Varianza_Desconocida.py
> +        if z < -buscarT(alpha / 2,n) or z > buscarT(alpha / 2,n):
```suggestion
        if z < -buscarT(alpha / 2, n) or z > buscarT(alpha / 2, n):
```

2022-11-21 02:12 UTC, angel-tapia commented on Media_Varianza_Desconocida.py
>  """
```suggestion
"""
<param> blablabla
```

2022-11-21 02:12 UTC, angel-tapia commented on Media_Varianza_Desconocida.py
> +    sigma = float(input(Ssigma + ": "))
```suggestion
    s = float(input("s: "))
```
Para varianza desconocida es con s la formula, tenemos que leer al igual los n datos y sacar su desviacion estandar

2022-11-21 02:12 UTC, angel-tapia commented on Media_Varianza_Desconocida.py
> +def prueba(z, operation, alpha, n):
```suggestion
"""
    <summary>
      Poner documentacion
    </summary>
    <param> variables </param>
"""
def prueba(z, operation, alpha, n):
```

2022-11-21 02:12 UTC, angel-tapia commented on Media_Varianza_Desconocida.py
> +        if z > buscarT(alpha,n):
```suggestion
        if z > buscarT(alpha, n):
```

2022-11-21 02:12 UTC, angel-tapia commented on Media_Varianza_Desconocida.py
> +        if z < -buscarT(alpha,n):
```suggestion
        if z < -buscarT(alpha, n):
```

2022-11-21 02:12 UTC, angel-tapia commented on Media_Varianza_Desconocida.py
> +    print("Prueb de hipotesis de una varianza conocida")
```suggestion
    print("Prueba de hipotesis de una varianza desconocida")
```

2022-11-21 02:12 UTC, angel-tapia commented on Media_Varianza_Desconocida.py
> +    xbarra = float(input(Sxbar + ": "))
```suggestion
    xbarra = float(input(Sxbar + ": "))
```

supongo que al igual es sacar la media con los n datos que nos dan, no?

2022-11-21 02:12 UTC, angel-tapia commented on Media_Varianza_Desconocida.py
> +    sigma = float(input(Ssigma + ": "))
o bien, podemos ignorar leer los n datos y hacerlo de esta manera, como prefieras

2022-11-21 02:12 UTC, angel-tapia commented on Media_Varianza_Desconocida.py
> +    prueba(z, ["<", ">", "!="][opcion - 1], alpha,n-1)
```suggestion
    prueba(z, ["<", ">", "!="][opcion - 1], alpha, n-1)
```

2022-11-21 02:25 UTC, JSuarezIbarra commented on Media_Varianza_Desconocida.py
> +    sigma = float(input(Ssigma + ": "))
yo digo que la desviación si se la podemos pedir como input, el profe siempre nos las daba

2022-11-21 02:33 UTC, angel-tapia commented on Media_Varianza_Desconocida.py
> +    sigma = float(input(Ssigma + ": "))
smnn

2022-11-21 02:47 UTC, angel-tapia commented on Media_Varianza_Desconocida.py
> +    xbarra = sumatoria/n
```suggestion
    print("Ahora introduce los n datos")
    for i in range(n):
        sumatoria = sumatoria + float(input())
    xbarra = sumatoria/n
```

2022-11-21 21:08 UTC, JSuarezIbarra commented on Media_Varianza_Desconocida.py
>  """
aqui no entiendo que quieres que ponga

2022-11-21 21:19 UTC, angel-tapia commented on Media_Varianza_Desconocida.py
>  """
Documentación sobre las variables utilizadas

2022-11-22 17:19 UTC, angel-tapia approved these changes

2022-11-22 17:19 UTC, merged